[project]
name = "fastapi-sqlmodel"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Luis Romano", email = "luisromano@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "bcrypt>=5.0.0",
    "fastapi[standard]>=0.141.1",
    "jwt>=1.4.0",
    "sqlmodel>=0.0.42",
]

[project.scripts]
fastapi-sqlmodel = "fastapi_sqlmodel:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
